# Generated by Django 4.2.7 on 2025-04-28 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackcomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Feedback Comment",
                "verbose_name_plural": "Feedback Comments",
            },
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="content",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="submitter",
        ),
        migrations.RemoveField(
            model_name="feedbackcomment",
            name="author",
        ),
        migrations.AddField(
            model_name="feedback",
            name="assigned_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin assigned to handle this feedback",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of the feedback",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo related to the feedback",
                null=True,
                upload_to="feedback_photos/",
                validators=[feedback.models.validate_image_file],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student who submitted the feedback",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedbackcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the comment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("infrastructure", "Infrastructure"),
                    ("administrative", "Administrative"),
                ],
                help_text="Category of the feedback",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the feedback was created"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the feedback was resolved", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("resolved", "Resolved")],
                default="pending",
                help_text="Current status of the feedback",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(
                help_text="Brief title of the feedback", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the feedback was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackcomment",
            name="comment",
            field=models.TextField(help_text="Comment text"),
        ),
        migrations.AlterField(
            model_name="feedbackcomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the comment was created"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackcomment",
            name="feedback",
            field=models.ForeignKey(
                help_text="The feedback this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="feedback.feedback",
            ),
        ),
    ]
