# Generated by Django 4.2.7 on 2025-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="year_of_study",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("admin", "Admin")],
                default="student",
                help_text="Type of user account (Student or Admin)",
                max_length=30,
            ),
        ),
    ]
